---
- hosts: default
  remote_user: kostas
  tasks:
    - name: install nginx
      sudo: yes
      apt: pkg=nginx state=latest
      notify:
        - start nginx
    - name: install git-core
      sudo: yes
      apt: pkg=git-core state=latest
    - name: install build-essential
      sudo: yes
      apt: pkg=build-essential state=latest
    - name: install cmake
      sudo: yes
      apt: pkg=cmake state=latest
    - name: build and install libsodium
      git: repo=ssh://git@github.com/ksophocleous/libsodium.git dest=/root/libsodium accept_hostkey=yes
    - name: builds libsodium
      command: mkdir -p /root/libsodium && cd /root/libsodium && cmake ..
  handlers:
    - name: start nginx
      service: name=nginx state=started
